language: node_js
node_js:
- '10'
before_install:
- curl -L -f -o "$HOME/git-duet-binaries.tar.gz" https://github.com/git-duet/git-duet/releases/download/0.6.0/linux_amd64.tar.gz
- mkdir "$HOME/git-duet"
- tar xzsf "$HOME/git-duet-binaries.tar.gz" -C "$HOME/git-duet"
- rm -rf "$HOME/git-duet-binaries"
- PATH="$HOME/git-duet:$PATH"
script:
- npm run test:ci
- npm run lint
- npm run acceptance-test
- npm run sonar-scanner -- -Dsonar.login="$SONAR_TOKEN"
env:
  secure: jC4MH9gADDRJLw+ZbpyzFs2HDuxCRuSxiSs83TkBIuPrvLuTbInoiggmHt8Ko2ZDr0ZMWV70RYZx8lkWKe5XZoZOxH1kkTfBpD4HRA32w6VQUpTLfT1K7tZ1MKAA5TeZLaBVczbyIfpeZ5zCIcAfE5Ev6t1oxh29QSfElMEhsiqTiWjaDVBA8Jof7rsPR/ffvawEU4DYul0kzVPmGZ7OtN3QXEswcFufcvCQXUMmw7D7Yqd5V1shVWhJg9F8th6VmaQ7w8wg+Z7ej+73Jg2NJO8c878a6fobicvpZAWAGw/wUo71+mIqHu6WZQXBeuqFW/yxU+FK0VGul9TSf6m+YIQ8b4psawJN7nvHcAaNiMGS3EkNWfn0an3I14g2AoWqEFIfExCsafVaynuw0GZuxxcYJ7LLSBkttI9JR1IhP50DYtFCuTHbAoqN18bEfyIx7XAvQLRG5binOOWyDtoYFtid9GWt/PsycmvC/UiaSGHy6d/NcHwr1U2U+lh/fQYWimUP35DrMjg2Xfvqxm7pkKSfHfdMSMbZEj0UvWQH6PpzCDZQL0o3fEwSLi1k5J4FM7KE0pu33mBB1/q8AQsFPQ9fQAKkyiovyHsAPYKSNyhw/3KZOmYkKg5h0gccCMCoWoLt/ZygvOzjJa5Of6JVDVOhv8ELPprFpw+cHFZKiQY=
