language: node_js
node_js:
- '10'
sudo: required
addons:
  apt:
    packages:
    - docker-ce
before_install:
- curl -L -f -o "$HOME/git-duet-binaries.tar.gz" https://github.com/git-duet/git-duet/releases/download/0.6.0/linux_amd64.tar.gz
- mkdir "$HOME/git-duet"
- tar xzsf "$HOME/git-duet-binaries.tar.gz" -C "$HOME/git-duet"
- rm -rf "$HOME/git-duet-binaries"
- PATH="$HOME/git-duet:$PATH"
script:
- npm run test:ci
- npm run lint:ci
- npm run acceptance-test
- docker image build -t jaedle/captain-spike:latest -f build.Dockerfile .
- npm run sonar-scanner -- -Dsonar.login="$SONAR_TOKEN"
before_deploy:
- docker image build -t jaedle/captain-spike:latest -f build.Dockerfile .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  on:
    branch: master
  script: docker push jaedle/captain-spike:latest
env:
  global:
  - secure: oTcT6q7oR+niEcfFE1aDDlUVBVpj5TOZVshhbS93VeShWiDPiKY06aHUsDdMGaCm8oeGog2yZJHvmanYqIz/QIa/6lA1V30qvH76D8vi7Y6EhWhp6hOxV2cF9WzYHSUvtae+S0eilwiRXmUrowGJHxeR2oLiObx0wUYAN+b7tiCARfX8kkwj9ZNm6W73mu2LcZkmYeOD2InluDNgsL6ztgtk0GuPPJHzcH2MUsa1S5lqgAjusZ0fYoVMmRmTPT7+7RVpeE15sVptOxVZkPqabHuc24uuM56pRYlONTtUGQPBUpzkUS9mH4DA62dMmJ0rdAGRB6+Q/3c0W9aa66pTkhjF/1FCnzqSy/3PEM9jUlScFTatwfQlmu82Voq+UxQbDkIpfm1DECUBV/gFQAdUwxXUB5Erwy2bCeEAnccBiEUAgf24F291hpqlTqNx8ZO7TE9Big493QmB1FSu6jI+SexdJNX75Kvrt55otBWV3Y2d/s8Vub5g9n6fWBL7ca69Wf0l1Lhe6TPN9LL70zsA0zUFL16k2bIRrHCXixIecpKAmsADD/v3OUZhAMMJKci1u1xUFmRyyAkwr7wZ4/DcFVBzChusAI4XdozISHUEumFKgKLUVXcbDrpIOG8ESSTbmRXxIN6kyzwySHukhYtI8DgyDZXjQZpViwy3I0DhgFc=
  - secure: TQF38hhmynRHFfag4FryEpv8Xj7lJJTdR8yw580QzCpGNbBqNHSwM/M2pjpPhAtGnEabxQFSJBjSFnIg1dQ+xWo3ywYa4+us52wQMaV61Jm2dCXSLKLvqb9F6r0nTbY4bYOIR/ivzvzbF1jpln7S1rbBHloEJYFFcfKwqduEbtCqRy+Q887FmGuS6hi8KSD3eShEHuerlCDJ44U9ezEfpcKeadv35SuhhP75LTnCgu/3F6FSsJ+p62LYY3TKVPaAzXlavdYcyYj9XMKbzTH3If7vJJq3CbLyqMgDT22lvgqQnu+Ktk4U/O4qzXe2jc97445JXitioxjeFCx/+94JPyAlgCJNm7XwVS9S9F8/BD6zmBEsgJWFqocXUWB+3vF5My1xAN4NQPbPqwTeWFvdltM1NY0KxmMMWHdq5JFn5dRnpeSN7R9Qhj5PUZIcJ6WpSnXSdDHrLx003LQwr9mdQNHQ9Esg7T/G18O+FyYVZyAm+Jvzhpf4Q7uaCLyRlVFpQQ9EUWbr8vjj4P2ycucO0ACez8/eTTC/vP24MurwQCzo0fgbcYH66dKZk6axslqFSH/J7jQLjYl8y3z414dz2+xrJNuJQA98kQSUVMXlPpntviHQYrAUk9mxHmA96m27yiRa2558BxViPFP7pq7cjODqZP7rDouu82A2YV7kN0s=
  - secure: GCnrYBGm2u0hPzfLsne91xMbD8yjaucTJQB6INKD8BPViukRmpD4a1VSEHTGyG3e1dVqvZMhXLnesXpAiHzpa6tdpZz4K0/K7sM+n+dCw+HX/j54C0L0nOISugBCtUUBen8lh0k7vn+IzNrFjYR0NXg7rd7B5jxEQNC/TVNrSneC5wFz/Nlo0iUHVXfZMSpqjrBf1/ZlrKi1IP1pNpUp1C4Z0XtvAqc1LYrnuRh1FoUjnFkCyiTuDhQKNtDsn+eOKCcagWS2KAIho3cvKGZipZGEyaefdbrvbMF3x9zAT48hc8K3+qKv2bTJtVBBns9SOONlEytXonNKSflA93bl0ikDt0T3Cw8W1fbb64kC6PigQemfZZF+jQ23sM+9iUoYFUxVLqIaRIwAlOpWfKbi9OnZyiU6wvoEn5d1fst02uFBgEntmI72LIq05sWrUTKu5CfZHTp5NgsKL0iji8as3AlxBhJDjtw+B5BbS2TK3J6Q77k9FGmF+m7At/sn84njw+XkMsSdfDLWHv2KrKAkY7C2Sgiis0w7qwTXcaqA1S3g+Xe5i6V2dW5TBvKZrN1B93KbV+TDO4wwSZCTODIJgbtp750FqPjpnVUTvqYjIyt2f9bD82IAFQ7SRGIvBqCE7phOhf5XWvA7ZyA0k40Q7Vs4ykipplEfq+f5a2H2fQk=
