language: node_js
node_js:
- '10'
before_install:
- curl -L -f -o "$HOME/git-duet-binaries.tar.gz" https://github.com/git-duet/git-duet/releases/download/0.6.0/linux_amd64.tar.gz
- mkdir "$HOME/git-duet"
- tar xzsf "$HOME/git-duet-binaries.tar.gz" -C "$HOME/git-duet"
- rm -rf "$HOME/git-duet-binaries"
- PATH="$HOME/git-duet:$PATH"
script:
- npm run test:ci
- npm run lint
- npm run acceptance-test
- npm run sonar-scanner -- -Dsonar.login="$SONAR_TOKEN"
env:
  global:
    secure: XARAok2351SO7q2IlyFjS5OJnCFNKSkINCDoAdR0S9gzT3lumpf74E88o4+ndLS29gBLLJMQ2ArM17P/46mwTeS+YwryDv5D7hgX4Ef08rVGWrK5QxQ994yMm7DPC7fXAAx6TYP2/HbbvaDcxrtPNdZOuwQygUsQt4pF+xJpgIAtrPFGkjIVqFP1rkM6nHFgMf1ArFovPQDZPb9In19o4J6gtKhPcm/YboGMSDL5Kj2QPAXBF45tCC20uSRRA4cTc/g5+yoD0Ey2k/xUY6jzaX9Rg/llKbKmK81uV3M3JDcj2BCS2NtFrIiKlyXc3L0vCT7leR/HAN6D+P0OVoLsE/cFErAUCMPSQS01Ra2xPkjJVSeOqXwFTqu9Dix8INYU4XvMNJJViPcY0E1Mmb7Ck8sq4p9njnyF2N/Y7HdrtVnLqoB6Cj5dW9LffkocgzVj+IY3ERacJ99quNZKaDxkJ8dXhV9j29GfKttUVzCT7yE6uoMnvs+fqg0kbr6JnPCuctQ14lSlGFQwe70EEq6G+GpSPF2eCa/nY2zdjlcT6/CpUXiyJILVjw1aJ5dUnzRrZYJWquKI64M0+d2XZSg4iugZFtbmi7EjDaLpKz8JqhMbr7J50aHMuAuZIuFyM6C4+j3E2UATpm7fd4doj25oI3QeCN7GeaK3Hu3ym0OWzTY=
