language: node_js
node_js:
- '10'
sudo: required
addons:
  apt:
    packages:
    - docker-ce
  sonarcloud:
    organization: jaedle-github
before_install:
- curl -L -f -o "$HOME/git-duet-binaries.tar.gz" https://github.com/git-duet/git-duet/releases/download/0.6.0/linux_amd64.tar.gz
- mkdir "$HOME/git-duet"
- tar xzsf "$HOME/git-duet-binaries.tar.gz" -C "$HOME/git-duet"
- rm -rf "$HOME/git-duet-binaries"
- PATH="$HOME/git-duet:$PATH"
script:
- npm run test:ci
- npm run lint:ci
- npm run acceptance-test
- docker image build -t jaedle/captain-spike:latest -f build.Dockerfile . --quiet
- sonar-scanner
- npm run codacy
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
- provider: script
  on:
    branch: master
  skip_cleanup: true
  script:
  - npx semantic-release
  - version="$(git describe --tags `git rev-list --tags --max-count=1` | sed 's/v//g')"
  - docker image tag jaedle/captain-spike:latest jaedle/captain-spike:${version}
  - docker push jaedle/captain-spike:latest
  - docker push jaedle/captain-spike:${version}
env:
  global:
  - secure: WD/nWj+y4ou8FHIdxrX8hRSVGEvOQfSOe5hNBw+FazMquMP00siss4xZKS/gfzjiIO3L8ctmG5l2u8iTII7Cw1TojjghXSVv7e/ds3SZbyPLx8AFw2Wud0EUEUDCt1pVuTxpkpqeJ3P86kEwh1cCqtFMK3Q/HrX+U5bhjZ3EXNVXmrEQ7YudbejqxqtxQKjAiZR6RjKnbx6mQKaWcs2xbUyoJIUBo6mQnHZQJPGPW5o6Ctdj79u//Mi0xXub+KXl1ZWgN2xaz4gG6M37lbS3BG9AOeEiJEvchZIgpIu4NaJbVzmmVvo3yor9AUb16BGt3CwUoGarJEo7N4Q2lm1/REhvorQpIC8oZJF64pLaTi4aXg44cCkTQCkP2ShRgAAQ0nrB0vgpj4XK1OCbjHrPOMUGC0ghBsoAeMA7nTZ/OB8vUzpS2y+rAXSDnMcxb/BtfbbMY6tYOhd8lXqW4q3Gm+Sa/GvN3SqwN1yJgxCayHtsWZSfpOHQhT+xAaCEu5XSWcKAwxQUyxvBgrpApXDn3x5NjGxiH9LVH8jUXYfb1VwIMYmBL6PnL6LvcO7yOQUa77TLdHx66UjintX7BDMgR2YKDubaa5yfmL3awmQMgqUtF9ao2A0vqCKdTLHGqpteu64Ycx8JODVwz8RvNkGAQSxeatfos/YhRyCg5jiN4Jc=
  - secure: gywOf3ysQkWMn1AwUX1J0MspVnAFpvdlENG+rbaC23WFFF1qMXUXr00OCLfcbdgFSfj9H3BkOkxP3Bl0x65EDgBNB0Lcs50yaztw+ILa0hvyZ+ygKs1Dtzddx/vae1xLTlpQMuWKpKgLe0pRSZInkGnF0wWORKi2JtUHe9Eu7eL7s2F3nD3bCmPgzaak6ZfvDl7yMu2JzdweYPRoNwcTEUEBwfOgYivWQ0EgH1CyHXTpIc5QqFmy0qIahSc6lhOQXC12XRpRdbG23F1t45xz10EPHl3+BPtx2gOZ1WFcsPndZQDLRpjE4hcD9X4qJZkrpyWPidXEyNLJA5zn3Nw1T3bJwsAAUUcdJOPCCMyCNYaw/tKLgjIWhfFSN//Xcv5n1uheUyzxs1ynPedNyc/a6jLz0feEJkbW+wnO3ZSKMdekA7BW4ENy/y1wY+LDcKEnMhXiyYNjQvl32AA57Yx0Eeyd+c98ElsSysXGX5S6lQWoL6Q3XZS62T8yaTYYSNQqNrjD8mm1Yzlq616DnytT2sBdIFknWH1PGXjyBsUrNpUXzmAYfGwuOychfUuJprACOJmIpyKEs63q3wGFYJaegzRFfUoJ8LyUvUlNhdLBG4Jw27JmlJKDWeejWol6a/V+MSoOk3Y+cxfWbt8PMwAyxgyym1pF0rEe+9rr21qjgUU=
  - secure: RRJKPAsGMCubEAyM5cI0fjsRHyzyy2uqTq9H0F9ID7/orSJ6cdP0IvHgJkuJqFNQ3402Voa5DMORmSHvb/05fRdfI6s5nYOEKA3WQmzoI/Q/+IBAyWid0WCxANyJW8HUpeFIyFIxHCAMe4DSNernnOTtIevY4WZqBsiEZ3RpT5NdbqfEV4G8OkyAv4hC/leSv1/96aQ52HIW4GTrs54CoRL/bLQeHtxcHeYfzF7HLdoKMr/Cx1UvoeWYzJvz2M4d+lpsxHx5bai7mo309VUDUD1gGqWDFCFgsAmkLKokgtCWYbp3Cfyy6q0+kLj6f8T+rbmqJbfJt9wzkaxcr8Vx35WwVJJNz+FVZe6jLdTxYzQXCPW5xJGboCXPO0LfEChD41NloSC+sUo2bjGGJwv2D56BLDk5jLWs1YW3HsYkQn1kLOId+qw8ElfC7I82JeyFscAQrycUp7WFuRQ5ZOaXNqyPISPLwOvq6nqRF9tAhKAv2oWjByhCP6+mJaK7IAaJ6bPy07gayEGebz1pPHMLDHrbUcEKmvvtzN3pi9CYrB6msgcvBjRXTTItgTv1H28PEtI/XqAbxW16u2fChSZylJQ9S0VuWn9yu4G5nKJD1GznM/LFigo6FlobVDkEfyHMxMMVLg+SmlRU8uLa4iG1wD3PQpl1Uykf2iyke4TXW5U=
  - secure: J+JYazQC885XouJIYMmkZ4rn+VkungVEkKXZyS4ZiWQ5dUoLkFd9Bv4YAEYFopTCVlHwbr3bcGxVYfMR3IBSD4ggwMCUlGdchJN8FID2O4wh6zod+w55x//A8bEkrBxJGcjAfDfT1b7mEYNZHCuNhXoEY+atJY2GU0fDXkKs+ch68OKCv0dXjVxuV6r66/6Zj8VoQYgBkTlvqbyl62e1V0JyqGvtcMf3kJSXzWty01j5q4JLGiILJI4/dYgM8rx8/BPHkby/gxwMt01lwFCaLOyh2J8i52Wy4uD7Tc8vX2SZzUfkMErnFsnU2ICa/GvuxKQ0xeUMKOqMESqrYT2ljeh2LjBewSwal+W6OoMz8i+Ur/wF/rwPrn95d5nrZffNQuVr+hy9HgefsZAtT/NBxLIFmcWVwSF9nT+O/paiEoJ4and312+0GTZ+ZngIAcey/zeF//Er1sJt2axnGan8EjnqPJ38ZSPTO4Fwf+Gk7PfNq2QuO0o0fs9y4unbvzD2gpkddfkI0Caw18Jly+LgIN9Ib69+Y91I1+Yo3iDl6N2qL4qKU5P7ksCBU3oSz3NQ26ei3tPymdgSF47qqGGNr5N0a2C4nfHiCH0HFRZatdtJKuYwFRDoFxpbGnEaLJL6jpEwXCWPiqhwwPfdLcKojSDXnwMtKWtUqXvwfrib9Y4=
  - secure: RRuFRN7R/aKGLUxVuog9pu9w5bKU/tj+2QG3epzpdmHsyfIsw6vnXl5axVfyup/4PszS2tJ5Qt9RkSOImru1DY7WAZjKbMSAMDEIN9U1kg5uaCliIAKV/DJVcGuCd6kvoS5HvR1Ml7jNu3TCOS4nvQG1vWAp0PTcoJ1mgMlM/R0m++UXg6zup86OuPOWNDD0pjXR/klTNBUB9CLpJe8YORFUn9XPp8KrOCmnCqYX4GiqV+Vjbeg8QjmNPQ+Ldxa2TwgFKzkdkx1mwHmDES4UT8PSq/JAM0A4hbiYABc0lM8yMyIpOfQNVN3upg0PIZ53lZdrDK7epdxBrES7s3ahho7mjSQ9co2bG3sYK8uE9W/ucySU1v7RM9vT95ffvdKAwnHZGdZ6Tv/2dTA0CbVzjoir0jACA/UpCqo58TEczDBUtvj/2mGtFQs6sY+Ma1cb0TMTseLSZcgfZfin7Jz6st3vl3fvovAjZOOOPHbZgh2MlNonF1doH67ynzGQUFCMK8hOVMUIBJJ4hNsZDpLkq4zlVN35CCOeh2XTt61dJTqNJOQummhcWPhEd7aBsCxjAd3JAV4pYC2NkRhsNNYMzz8idU21OleIx2MemLDtrvNJImRi5CRGKz/lSGIm3Px6Etb0gd3BM4LfzMExyGy+s5VmLeo6BfSLU81hEvaRUPo=
  - secure: eNFbvbObU/uxYzqV8nxVNd2v0Lsbg1JIL8dqQPAYVwr3EWNRP4aeEL+fX3EB/I56tmpFdadS5yU7Y9AKJrA3I9fmw210HfACei//xCBwQCtPSkVFewzJu0RobJaAAuCF9AFkXd/DvaH1YERZjmzfhK+JoP9F/88eJh3TA6Phcuu/0z6Dw7SU2KYsypYSaYs2Leq+DUAMZg/M9mLYixzmP+aPqtRWWAJ/ngEZEUQW3MuDEd/IhhVUz5GLzG25arxTSiJjpxD3+ICrIiVkPHD05HnCSLRCkA4k641L4XIqtzok773DljRttlZfkQMMdztcBUGWXgZC6Jkutk0T8ifaUe8CUZxShNMtu7d8sCa47+J8O3DMFfv/T4ik12ONFEpeXIVINvHnCTYLf+NMkmjEaIRhsvreamjpUZX2DBh3Kb9RbpoofbG5w1rGIZIXSCA45QNGTyF6TXpxLiOdeGFQ4NOv2DW/nzJZ62QXQp9UcVcBlf6IJfYViVQg6Gg32y/THWBcj2HXOaTDzWJScI9JXGSxlfeEm+ioYsgTHMKc0aXcZcecKVxu8OiOZ4mbuy9NMmynwiR8/B1c75EYBz+ySOLB35+0PlCEhd5qYkFSVR2AoR6J1vcIDx4KtKnpdCxI4ENMtYspnD7gFSlg0i9pkbEnjlEhPD8xKyA1B/IpO7c=
