language: node_js
node_js:
- '10'
sudo: required
addons:
  apt:
    packages:
    - docker-ce
before_install:
- curl -L -f -o "$HOME/git-duet-binaries.tar.gz" https://github.com/git-duet/git-duet/releases/download/0.6.0/linux_amd64.tar.gz
- mkdir "$HOME/git-duet"
- tar xzsf "$HOME/git-duet-binaries.tar.gz" -C "$HOME/git-duet"
- rm -rf "$HOME/git-duet-binaries"
- PATH="$HOME/git-duet:$PATH"
script:
- npm run test:ci
- npm run lint:ci
- npm run acceptance-test
- docker image build -t jaedle/captain-spike:latest -f build.Dockerfile .
- npm run sonar-scanner -- -Dsonar.login="$SONAR_TOKEN"
before_deploy:
- docker image build -t jaedle/captain-spike:latest -f build.Dockerfile .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  on:
    branch: master
  script: docker push jaedle/captain-spike:latest
env:
  global:
  - secure: WD/nWj+y4ou8FHIdxrX8hRSVGEvOQfSOe5hNBw+FazMquMP00siss4xZKS/gfzjiIO3L8ctmG5l2u8iTII7Cw1TojjghXSVv7e/ds3SZbyPLx8AFw2Wud0EUEUDCt1pVuTxpkpqeJ3P86kEwh1cCqtFMK3Q/HrX+U5bhjZ3EXNVXmrEQ7YudbejqxqtxQKjAiZR6RjKnbx6mQKaWcs2xbUyoJIUBo6mQnHZQJPGPW5o6Ctdj79u//Mi0xXub+KXl1ZWgN2xaz4gG6M37lbS3BG9AOeEiJEvchZIgpIu4NaJbVzmmVvo3yor9AUb16BGt3CwUoGarJEo7N4Q2lm1/REhvorQpIC8oZJF64pLaTi4aXg44cCkTQCkP2ShRgAAQ0nrB0vgpj4XK1OCbjHrPOMUGC0ghBsoAeMA7nTZ/OB8vUzpS2y+rAXSDnMcxb/BtfbbMY6tYOhd8lXqW4q3Gm+Sa/GvN3SqwN1yJgxCayHtsWZSfpOHQhT+xAaCEu5XSWcKAwxQUyxvBgrpApXDn3x5NjGxiH9LVH8jUXYfb1VwIMYmBL6PnL6LvcO7yOQUa77TLdHx66UjintX7BDMgR2YKDubaa5yfmL3awmQMgqUtF9ao2A0vqCKdTLHGqpteu64Ycx8JODVwz8RvNkGAQSxeatfos/YhRyCg5jiN4Jc=
  - secure: gywOf3ysQkWMn1AwUX1J0MspVnAFpvdlENG+rbaC23WFFF1qMXUXr00OCLfcbdgFSfj9H3BkOkxP3Bl0x65EDgBNB0Lcs50yaztw+ILa0hvyZ+ygKs1Dtzddx/vae1xLTlpQMuWKpKgLe0pRSZInkGnF0wWORKi2JtUHe9Eu7eL7s2F3nD3bCmPgzaak6ZfvDl7yMu2JzdweYPRoNwcTEUEBwfOgYivWQ0EgH1CyHXTpIc5QqFmy0qIahSc6lhOQXC12XRpRdbG23F1t45xz10EPHl3+BPtx2gOZ1WFcsPndZQDLRpjE4hcD9X4qJZkrpyWPidXEyNLJA5zn3Nw1T3bJwsAAUUcdJOPCCMyCNYaw/tKLgjIWhfFSN//Xcv5n1uheUyzxs1ynPedNyc/a6jLz0feEJkbW+wnO3ZSKMdekA7BW4ENy/y1wY+LDcKEnMhXiyYNjQvl32AA57Yx0Eeyd+c98ElsSysXGX5S6lQWoL6Q3XZS62T8yaTYYSNQqNrjD8mm1Yzlq616DnytT2sBdIFknWH1PGXjyBsUrNpUXzmAYfGwuOychfUuJprACOJmIpyKEs63q3wGFYJaegzRFfUoJ8LyUvUlNhdLBG4Jw27JmlJKDWeejWol6a/V+MSoOk3Y+cxfWbt8PMwAyxgyym1pF0rEe+9rr21qjgUU=
  - secure: RRJKPAsGMCubEAyM5cI0fjsRHyzyy2uqTq9H0F9ID7/orSJ6cdP0IvHgJkuJqFNQ3402Voa5DMORmSHvb/05fRdfI6s5nYOEKA3WQmzoI/Q/+IBAyWid0WCxANyJW8HUpeFIyFIxHCAMe4DSNernnOTtIevY4WZqBsiEZ3RpT5NdbqfEV4G8OkyAv4hC/leSv1/96aQ52HIW4GTrs54CoRL/bLQeHtxcHeYfzF7HLdoKMr/Cx1UvoeWYzJvz2M4d+lpsxHx5bai7mo309VUDUD1gGqWDFCFgsAmkLKokgtCWYbp3Cfyy6q0+kLj6f8T+rbmqJbfJt9wzkaxcr8Vx35WwVJJNz+FVZe6jLdTxYzQXCPW5xJGboCXPO0LfEChD41NloSC+sUo2bjGGJwv2D56BLDk5jLWs1YW3HsYkQn1kLOId+qw8ElfC7I82JeyFscAQrycUp7WFuRQ5ZOaXNqyPISPLwOvq6nqRF9tAhKAv2oWjByhCP6+mJaK7IAaJ6bPy07gayEGebz1pPHMLDHrbUcEKmvvtzN3pi9CYrB6msgcvBjRXTTItgTv1H28PEtI/XqAbxW16u2fChSZylJQ9S0VuWn9yu4G5nKJD1GznM/LFigo6FlobVDkEfyHMxMMVLg+SmlRU8uLa4iG1wD3PQpl1Uykf2iyke4TXW5U=
