language: node_js
dist: trusty
addons:
  sonarcloud
node_js:
- '10'
before_install:
- curl -L -f -o "$HOME/git-duet-binaries.tar.gz" https://github.com/git-duet/git-duet/releases/download/0.6.0/linux_amd64.tar.gz
- mkdir "$HOME/git-duet"
- tar xzsf "$HOME/git-duet-binaries.tar.gz" -C "$HOME/git-duet"
- rm -rf "$HOME/git-duet-binaries"
- PATH="$HOME/git-duet:$PATH"
- sonar-scanner -Dsonar.login="$SONAR_TOKEN"
script:
- npm run test:ci
- npm run lint
- npm run acceptance-test
env:
  global:
    secure: zXXn8ZJWkHJdI/tCuWCFlqiROJWNx8vwJWBkZJnrtMDPpQ2xQR2adq72ZxSe+KIALk/UfgWifnvKIQfM1sv95Pa9eKWIenUXV3qhef3k69Ez6CWlBnHtxwdNjvGoWOQmqH7CgWCJ9ERt4sy/kArpd5RP5w2vpzXQS2MEIGR0IgCA3CdUFBT+KuaZjdfJIFafrc4md55jE1ORWPf5H1IJKb+WZbg2Vmdo338h8/NfyFQ1fGtWu4o8yc8K9hfbYDJ4Y+UCcSXplTgMLFpjvWypqu4YOjNkCBffWUq+cXsn7LJKTb8uW7bxX98+ZBoVg+yBkbHC1w5bRBRwO7U01RV3YYIh+ANcSzDsXyS93oGR+9sxFksw8zQKe7DbDINk4AucEOl3u2602TOmv41H8xdbyGaaWYGdOc9lXHHmv8KsoT8OGnkX8eNbNbbRTw/zZUr8M36nLVu22qrl2IA5XdLDtQBgybEIJ8QlO7n432AmoUxcGlvwaHIh1peds331uiaK/pj8Yg/mmCtk5orQX42/SSpGlH+5R67HOeySP9B5rrb0bgTmGFOwVrDOGCNnH5H/oqkXXzpEdLykszPlZVCLVkONDuuMR0k5ibuK63AT4C4ZOsa25WAAfi3T6hWyGvsqorJD8EYJUYgdqLNHMXw2IakRqMxHjLAEnERBYzs9PoI=
